from __future__ import annotations

import asyncio
import datetime as dt
import re
import uuid
from pathlib import Path
from typing import ClassVar

import yaml
from rich.text import Text
from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Container
from textual.screen import Screen
from textual.widgets import DataTable, Footer, Header, Input, Label, RichLog

from llm_agent.app_integration import create_and_save_rule
from llm_agent.rules_store import RulesStore


def _make_rule_id(query: str) -> str:
    """Build a unique, filename-safe rule id from the user's query."""
    slug = re.sub(r"[^a-z0-9]+", "_", query.lower()).strip("_")[:30] or "rule"
    return f"{slug}_{uuid.uuid4().hex[:6]}"


class MainScreen(Screen[None]):
    BINDINGS: ClassVar = [
        # ctrl+ combos so they still work while the Input has focus
        Binding("ctrl+r", "refresh", "Refresh"),
        Binding("ctrl+n", "focus_input", "New rule", show=True),
    ]

    def __init__(self, rules_dir: Path) -> None:
        super().__init__()
        self.rules_dir = rules_dir
        self.store = RulesStore(rules_dir)

    def compose(self) -> ComposeResult:
        self._rules_table = DataTable(id="rules-table", cursor_type="row")
        self._chat_log = RichLog(id="chat-log", markup=True, wrap=True)

        yield Header()
        with Container(id="body"):
            with Container(id="rules-panel"):
                yield Label("Rules", id="rules-title")
                yield self._rules_table
            with Container(id="chat-column"):
                yield self._chat_log
                with Container(id="composer"):
                    yield Input(placeholder="Ask for a rule…", id="chat-input")
        yield Footer()

    def on_mount(self) -> None:
        self._rules_table.add_columns("Name", "ID", "Created")
        self._populate_rules()
        self._chat_log.write(Text("rulebox — type a query to create a rule"))
        self.query_one("#chat-input", Input).focus()

    def _populate_rules(self) -> None:
        self._rules_table.clear()

        rows = [
            (rule.name, rule.id, rule.created_at[:10]) for rule in self.store.load()
        ]

        # Rules generated by Gemini are saved as YAML, which RulesStore doesn't read
        for path in sorted(self.rules_dir.glob("*.yaml")):
            try:
                data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
            except yaml.YAMLError:
                continue
            if not isinstance(data, dict):
                continue
            created = dt.datetime.fromtimestamp(
                path.stat().st_mtime, tz=dt.UTC
            ).strftime("%Y-%m-%d")
            rows.append((path.stem, str(data.get("rule_id", path.stem)), created))

        if not rows:
            self._chat_log.write(Text("No rules in LM-rules/ yet"))
        for row in rows:
            self._rules_table.add_row(*row)

    def action_refresh(self) -> None:
        self._populate_rules()
        self._chat_log.write(Text("refreshed"))

    def action_focus_input(self) -> None:
        self.query_one("#chat-input", Input).focus()

    async def on_input_submitted(self, event: Input.Submitted) -> None:
        query = event.value.strip()
        if not query:
            return

        chat_input = event.input
        chat_input.value = ""
        chat_input.disabled = True  # prevent double-submits while the model runs

        rule_id = _make_rule_id(query)

        # Text(...) instead of an f-string so user input can't be parsed as markup
        self._chat_log.write(Text(f"You: {query}"))
        self._chat_log.write(
            Text(f"Agent: Asking Gemini to write YAML for '{rule_id}'...")
        )

        def _status(message: str) -> None:
            # create_and_save_rule runs in a worker thread; hop back onto the
            # Textual event loop to surface live progress instead of a blank wait.
            self.app.call_from_thread(self._chat_log.write, Text(f"Agent: {message}"))

        try:
            # The LLM call is blocking, so run it in a worker thread to keep the UI alive
            outcome = await asyncio.to_thread(
                create_and_save_rule,
                query,
                rule_id,
                self.rules_dir,
                on_status=_status,
            )
        except Exception as exc:  # noqa: BLE001
            self._chat_log.write(Text(f"Agent: Something went wrong: {exc}"))
        else:
            if outcome.saved:
                self._chat_log.write(
                    Text(f"Agent: Success! {outcome.rule_id}.yaml is saved and ready.")
                )
                # Stage 1 near-duplicate flags: informational only, human decides.
                for finding in outcome.similarities:
                    note = (
                        f"Agent: Note -- this may be a near-duplicate of "
                        f"{finding.existing} (class {finding.class_name}, "
                        f"similarity {finding.similarity:.2f}). "
                        f"Shared ops: {', '.join(finding.shared_signatures)}. "
                    )
                    if finding.differing_thresholds:
                        note += (
                            "Differs only in: "
                            + "; ".join(finding.differing_thresholds)
                            + "."
                        )
                    note += (
                        " Keep both, discard the new rule, or ask Gemini to edit it."
                    )
                    self._chat_log.write(Text(note))
                self._populate_rules()  # show the new rule in the table
            else:
                self._chat_log.write(
                    Text(
                        "Agent: Oops, the AI made a grammar mistake. "
                        "Try asking differently."
                    )
                )
        finally:
            chat_input.disabled = False
            chat_input.focus()
